repositories:
    - name: dts
      url: https://helm.dts-stn.com
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: benefits-finder
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/Benefits-Finder@helm/charts?ref=main
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 

releases:
# benefits-finder
  - name: benefits-finder-{{ .Environment.Name }}
    chart: ../helm/charts/benefits-finder
    version: 0.0.1
    values:
      - overrides/benefits-finder.yaml.gotmpl
    labels:
        category: dts
        app: benefits-finder
        tier: server
    namespace: benefits-finder-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false