# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}

      - name: Linting formatting
        run: npm run lint:formatting
        env:
          CI: true

      - name: Linting rules
        run: npm run lint:rules

      - name: Unit tests
        run: npm run test:unit
        env:
          CI: true

      - name: Cypress E2E
        uses: cypress-io/github-action@v2
        env:
          CI: true
          NODE_ENV: production
        with:
          install: false
          start: npm run start
